---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: senthil123/tomcatuidemo:4
        imagePullPolicy: Always
        name: myweb

---
---
apiVersion: v1
kind: Service 
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  selector:
    app: myweb    
  type: NodePort
  ports:
  - nodePort: 31123
    port: 8080
    targetPort: 8080
